version: '3.8'
services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    networks:
      - bot-network


  bot:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env

networks:
  bot-network:
    name: bot-network
    driver: bridge

volumes:
  postgresdata:
    name: mongodbdata
