version: '3.8'
services:

  ydb-local:
    image: cr.yandex/yc/yandex-docker-local-ydb:latest
    hostname: localhost
    volumes:
      - ydb_serts:/ydb_certs
    environment:
      - YDB_LOCAL_SURVIVE_RESTART=True
      - YDB_DEFAULT_LOG_LEVEL=NOTICE
      - GRPC_TLS_PORT=2135
      - GRPC_PORT=2136
      - MON_PORT=8765
      - YDB_USE_IN_MEMORY_PDISKS=true
    ports:
      - "2136:2136"
      - "2135:2135"
      - "8765:8765"


  bot:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env

networks:
  bot-network:
    name: bot-network
    driver: bridge

volumes:
  ydb_serts:
    name: ydb_serts