version: '3.8'
services:

  postgres:
    image: postgres:13.2-alpine
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bot-network
    restart: on-failure
    env_file:
      - .env

networks:
  bot-network:
    name: bot-network
    driver: bridge

volumes:
  postgresdata:
    name: postgresdata
