"""init

Revision ID: 19d30f04290c
Revises: 
Create Date: 2021-11-18 01:15:42.887218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d30f04290c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('intro', sa.String(), nullable=True),
    sa.Column('outro', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pack', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('started', 'finish', name='interviewstate'), nullable=True),
    sa.Column('question', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pack'], ['packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_user_id'), 'interviews', ['user_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pack', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pack'], ['packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_pack'), 'questions', ['pack'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview', sa.Integer(), nullable=False),
    sa.Column('question_file_id', sa.String(), nullable=False),
    sa.Column('answer_file_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['interview'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_interview'), 'answers', ['interview'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_interview'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_questions_pack'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_interviews_user_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_table('packs')
    # ### end Alembic commands ###
